Added new function: 'amLoggedInAs' to login a user (and more)
Codeception/module-symfony pull request #11
Opened 2020-09-05 19:59 UTC by TavoNiievez

Related to [Codeception issue 5699](https://github.com/Codeception/Codeception/issues/5699)

 - [x] Added new function: `amLoggedInAs` to login a user. 

<details>
  <summary>Click to see added function.</summary>

```php
    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
    {
        $container = $this->_getContainer();
        if (!$container->has('session')) {
            return;
        }

        $session = $this->grabService('session');

        if ($this->config['guard']) {
            $token = new PostAuthenticationGuardToken($user, $firewallName, $user->getRoles());
        } else {
            $token = new UsernamePasswordToken($user, null, $firewallName, $user->getRoles());
        }

        if ($firewallContext) {
            $session->set('_security_'.$firewallContext, serialize($token));
        } else {
            $session->set('_security_'.$firewallName, serialize($token));
        }

        $session->save();

        $cookie = new Cookie($session->getName(), $session->getId());
        $this->client->getCookieJar()->set($cookie);
    }
```

</details>

```php
        $user = $I->grabEntityFromRepository(User::class, ['email' => 'john_doe@gmail.com']);
        $I->amLoggedInAs($user);
```

- [x] Added [guard](https://symfony.com/components/Guard) config, in case the authentication system is based on it.
```diff
    public $config = [
        'app_path' => 'app',
        'var_path' => 'app',
        'kernel_class' => null,
        'environment' => 'test',
        'debug' => true,
        'cache_router' => false,
        'em_service' => 'doctrine.orm.entity_manager',
        'rebootable_client' => true,
        'mailer' => self::SWIFTMAILER,
+        'guard' => false
    ];
```

- [x] Added `SymfonyModuleInterface` to improve for clarity.

<details>
  <summary>Click to see added interface.</summary>

```php
interface SymfonyModuleInterface extends DoctrineProvider, PartedModule
{
    public function _after(TestInterface $test);

    public function _before(TestInterface $test);

    public function _getContainer();

    public function _getEntityManager();

    public function _initialize();

    public function _parts();

    public function amOnRoute($routeName, array $params = []);

    public function dontSeeEmailIsSent();

    public function grabService($service);

    public function invalidateCachedRouter();

    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null);

    public function onReconfigure($settings = []);

    public function persistService($serviceName, $isPermanent = false);

    public function rebootClientKernel();

    public function runSymfonyConsoleCommand($command, $parameters = [], $consoleInputs = [], $expectedExitCode = 0);

    public function seeCurrentRouteIs($routeName, array $params = []);

    public function seeEmailIsSent($expectedCount = null);

    public function seeInCurrentRoute($routeName);

    public function unpersistService($serviceName);
}
```

</details>

- [x] Updated dependencies (as far as possible).
- [x] Updated docs.
- [x] Improved compatibility logic:
```diff
- //Alias for Symfony < 4.3
- if (!class_exists('Symfony\Component\HttpKernel\HttpKernelBrowser') && class_exists('Symfony\Component\HttpKernel\Client')) {
+ if (Kernel::VERSION_ID < 40300) {
    class_alias('Symfony\Component\HttpKernel\Client', 'Symfony\Component\HttpKernel\HttpKernelBrowser');
}
```

@Naktibalda waiting for review.

2020-09-06 06:09 UTC, Naktibalda requested changes

2020-09-06 06:09 UTC, Naktibalda commented on src/Codeception/Module/SymfonyModuleInterface.php
> +    public function _parts();
What's the purpose of this interface? Is it documentation?

* Standard hooks that are common to all modules are defined in parent class [Codeception\Module](https://github.com/Codeception/Codeception/blob/4.1.6/src/Codeception/Module.php#L202-L266) and documented in https://codeception.com/docs/06-ModulesAndHelpers#Hooks
* It repeats methods of [DoctrineProvider](https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Lib/Interfaces/DoctrineProvider.php) and [PartedModule ](https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Lib/Interfaces/PartedModule.php) interfaces.
* `onReconfigure` method should be protected, it wasn't supposed to be called directly.
* Other methods are Symfony specific methods implemented by this module, so they are defined in Symfony.php file.

2020-09-06 13:07 UTC, TavoNiievez commented on documentation.md
>  ### amOnRoute
Fixed in [b3335e4](https://github.com/Codeception/module-symfony/pull/11/commits/b3335e4bada3b10a9311840001383eb831a34301). Thank you for explaining to me.

2020-09-06 13:08 UTC, TavoNiievez commented on src/Codeception/Lib/Connector/Symfony.php
> +if (Kernel::VERSION_ID < 40300) {
I think the same, sadly [it is not possible.](https://github.com/symfony/symfony/issues/35363)

2020-09-06 13:10 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +        'guard' => false
Fixed in [17f01e1](https://github.com/Codeception/module-symfony/pull/11/commits/17f01e1c294abbadb174a8c00a81cc4e24f2dd04).

2020-09-06 13:11 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
Fixed in [7680646](https://github.com/Codeception/module-symfony/pull/11/commits/768064621b0929d6db77c909588cc0f443f00dfc).

2020-09-06 13:14 UTC, TavoNiievez commented on src/Codeception/Module/SymfonyModuleInterface.php
> +    public function _parts();
Fixed in [34f06de](https://github.com/Codeception/module-symfony/pull/11/commits/34f06de2900e2714da8160ef5c6301e32cee396e). It is only for documentation, thanks to this interface it is clearer to see which public methods this module really provides and allows detecting details such as `onReconfigure` that had been overlooked, I hope it will be helpful.

2020-09-06 13:50 UTC, TavoNiievez commented on src/Codeception/Module/SymfonyModuleInterface.php
> +    public function _parts();
@Naktibalda I was thinking, wouldn't it be great if the [Codeception page](https://codeception.com/docs/modules/Symfony) showed only the methods provided by this module (that are described in the interface)? In a future PR, would it be possible to move all that documentation from the code to the interface, and configure robo so that it only reads that documentation, without bringing the methods of the parent class?

2020-09-07 12:48 UTC, DavertMik commented on src/Codeception/Module/SymfonyModuleInterface.php
> +    public function _parts();
Yeah, I agree with @Naktibalda that this interface is not needed unless there are different classes to implement.

As of documentation - if you make public method - it will be available in documentation. If you want it to be skipped just use underscore prefix _ to make this method hidden

2020-09-07 15:52 UTC, Naktibalda commented on src/Codeception/Module/SymfonyModuleInterface.php
> +    public function _parts();
> I was thinking, wouldn't it be great if the Codeception page showed only the methods provided by this module (that are described in the interface)?

I think that it is a bad idea. The primary purpose of framework module is to implement connector for InnerBrowser which provides standard methods for functional testing.

2020-09-07 16:01 UTC, Naktibalda requested changes

2020-09-07 16:19 UTC, TavoNiievez commented on src/Codeception/Module/SymfonyModuleInterface.php
> +    public function _parts();
Fixed in [1e86a95.](https://github.com/Codeception/module-symfony/pull/11/commits/1e86a958b5e96d4b7e32778b5fc59d3766449e22) @DavertMik and @Naktibalda, yeap, i get your point, again, thanks for explaining 👍

2020-09-07 16:19 UTC, TavoNiievez commented on composer.json
> -        "vlucas/phpdotenv": "^3.6"
Fixed in [1fffcb1.](https://github.com/Codeception/module-symfony/pull/11/commits/1fffcb1a2d7013637c8800a2cb28c8101be361db)

2020-09-07 16:43 UTC, c33s requested changes
as i am no member here i just post my personal opinion. this PR is much better than the last one but still has things touched which have nothing to do with the functionality. simply don't  do "and more" to the minimum and make the reviewers life easier. just my 2cts

2020-09-07 16:43 UTC, c33s commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
as i wrote i the other PR, i am not sure if it is a good idea to go for the bleeding edge implementation of the login code.


since symfony 5.1 the login for testing is done like this:
```php
public function testVisitingWhileLoggedIn()
{
    $client = static::createClient();
    $userRepository = static::$container->get(UserRepository::class);

    // retrieve the test user
    $testUser = $userRepository->findOneByEmail('john.doe@example.com');

    // simulate $testUser being logged in
    $client->loginUser($testUser);

    // test e.g. the profile page
    $client->request('GET', '/profile');
    $this->assertResponseIsSuccessful();
    $this->assertSelectorTextContains('h1', 'Hello John!');
}
```
https://symfony.com/doc/5.1/testing/http_authentication.html
https://symfony.com/doc/5.1/testing.html#testing-logging-in-users


before you had to do this:
```php
public function loggedInAs($user = 'admin', $firewallContext = 'main', $roles = ['ROLE_SUPER_ADMIN', 'ROLE_ADMIN', 'ROLE_USER', 'ROLE_SONATA_ADMIN'])
{
    /** @var Session $session */
    $session = $this->getContainer()->get('session');
    $client = $this->getClient();

    $token = new UsernamePasswordToken($user, null, $firewallContext, $roles);
    $session->set('_security_'.$firewallContext, serialize($token));
    $session->save();
    $cookie = new Cookie($session->getName(), $session->getId());
    $client->getCookieJar()->set($cookie);
}
```
https://symfony.com/doc/5.0/testing/http_authentication.html

i have not tested if the new code is backward compatible but maybe there is a BC break. also i still think it is handy
to allow to login by role and not by user. both approaches are valid but in many of my projects i only care for roles a
user has and not for fetching a real user. i simply want to know if a admin can create/view/edit/delete an object while
an editor only is allowed to create/view and a user only is allowed to view.

so if the old approach also works for symfony 5.1+ i would go for the old approach and add some helper methods or a 2nd
method to allow to provide a user interface

2020-09-07 16:43 UTC, c33s commented on composer.json
> +        "codeception/module-asserts": "^1.3",
may i again ask you why you require higher versions for this? have you verified not to produce a BC break by increasing the versions?

2020-09-07 16:43 UTC, c33s commented on composer.json
> +        "vlucas/phpdotenv": "^4.1"
here you do a major version upgrade. why? is there a BC break? do you even touch the phpdotenv component in your PR?
if the new version is required can it coexist with the old version? `^3.6|^4.1`

2020-09-07 16:43 UTC, c33s commented on composer.json
> -        "codeception/module-asserts": "dev-master | ^1.0",
i assume dev-master is also allowed if requested is it?

2020-09-07 16:43 UTC, c33s commented on composer.json
> +    "homepage":"https://codeception.com/",
cosmetic changes still should be in their own PR

2020-09-07 16:43 UTC, c33s commented on src/Codeception/Module/SymfonyModuleInterface.php
> +<?php
please drop the interface, it's simply not needed

2020-09-07 16:43 UTC, c33s commented on src/Codeception/Module/Symfony.php
> -use Codeception\Lib\Framework;
such use reorderings are also easier to review if they happen in their own PR

2020-09-07 16:43 UTC, c33s commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
how to handle in memory user or basic auth? 
```yaml
security:
    providers:
        in_memory:
            memory:
                users:
                    mymemoryuser:
                        password: "my secret password"
                        roles: 'ROLE_SUPER_ADMIN'
```

having only the user interface option require me to mock a nonexisting user class or the interface.

2020-09-07 16:48 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
@c33s the same logic works in symfony 5.1. I try it. What the documentation says is that this logic is no longer necessary because the method you describe in symfony / phpunit-bridge was included by default. But that doesn't create any BC.

2020-09-07 16:58 UTC, TavoNiievez commented on composer.json
> +        "vlucas/phpdotenv": "^4.1"
this has already been requested in another comment, please do not spam.

2020-09-07 16:59 UTC, TavoNiievez commented on src/Codeception/Module/SymfonyModuleInterface.php
> +<?php
again, this has already been commented, please do not spam.

2020-09-07 17:31 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
@c33s Regarding what you say about in_memory, in effect it is a totally valid and different form of authentication, and in fact it is already possible if you create a `security.yaml` file only for the `test` environment and get it to be imported in Codeception. I agree that it would be a good idea to add documentation on this.

2020-09-07 17:56 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
@c33s Regarding what you say about in_memory, in effect it is a totally valid and different form of authentication, and it is possible if you get the `security.yml` file specific to the `test environment` to be imported or you modify the symfony configuration for the test on the way. I agree that it would be a good idea to add documentation on this.

2020-09-07 18:29 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
@c33s Currently it is difficult to delegate tests to the CI server since the build fails in the installation of dependencies, this happens before this PR, and since before updating to Symfony 5.1 in [Codeception/symfony-demo](https://github.com/Codeception/symfony-demo), can you help to solve them? that way anyone who sends a PR could add the corresponding tests.

2020-09-08 00:48 UTC, TavoNiievez commented on composer.json
> -        "vlucas/phpdotenv": "^3.6"
Fixed in [e5c62ae.](https://github.com/Codeception/module-symfony/pull/11/commits/e5c62ae417e4694803a1e58b2bd726a280f2e568). Unfortunately version 5 is not supported yet by codeception and generates [the error mentioned in this issue.](https://github.com/Codeception/Codeception/issues/5946
)

2020-10-02 01:33 UTC, TavoNiievez commented on composer.json
> +    "homepage":"https://codeception.com/",
@c33s thanks you

2020-10-02 01:34 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> -use Codeception\Lib\Framework;
i had it in mind since then, thanks you

2020-10-02 01:36 UTC, TavoNiievez commented on composer.json
> -        "codeception/module-asserts": "dev-master | ^1.0",
@c33s not recommended

2020-10-02 01:37 UTC, TavoNiievez commented on composer.json
> +        "codeception/module-asserts": "^1.3",
@c33s yes, I have verified.

2020-10-02 01:47 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +    public function amLoggedInAs(UserInterface $user, $firewallName = 'main', $firewallContext = null)
@c33s Thanks for your interest in this, [thanks to this](https://github.com/Codeception/symfony-demo/commit/b469dcc81d65ef6c16fc5839bc1f07858730301d) everything works fine again, please let me know about any other concerns.
Regarding the function you are requesting, if you open an issue requesting that feature, I will gladly spend time developing another function with the specific API that you propose.
Cheers!

2020-10-02 01:47 UTC, TavoNiievez commented
@Naktibalda @DavertMik

2020-10-02 11:41 UTC, DavertMik approved these changes

2020-10-02 11:42 UTC, DavertMik commented
Looks good to me. I think we can merge it and publish next release!

2020-10-17 00:43 UTC, TavoNiievez commented
@Naktibalda

2020-10-28 13:41 UTC, TavoNiievez commented
@Naktibalda (?)

2020-10-30 08:54 UTC, Naktibalda commented
@TavoNiievez I merged 2 pull requests, not all others have merge conflicts.

2020-10-30 08:56 UTC, TavoNiievez commented
@Naktibalda I'll fix them today, thanks you

2020-10-30 09:42 UTC, TavoNiievez commented
@Naktibalda 
I lost the ability to update the fork i created these PRs with.
I'm sure the conflicts are white space issues at the end of the file,
but GitHub no longer gives me the permission to fix the conflicts :confused:

2020-10-30 19:17 UTC, Naktibalda commented
I merged these changes manually too.
I will make a few more changes and release a new version this weekend.

2020-10-30 19:17 UTC, closed without merging