Added "See also"
Codeception/module-symfony pull request #120
Opened 2021-03-15 13:19 UTC by ThomasLandauer

I shortened the example, cause `$emails[0]->getTo()[0];` looks strange ;-) Instead, I added the "See also"-links which (I think) are a good idea in general since the page gets longer and longer, so it's harder to get an overview what functions do exist at all...

The `@var` annotation syntax is taken from https://phpstan.org/writing-php-code/phpdoc-types#general-arrays - I'm not 100% sure if this is the right way.

The closing `*/` in my new `@var` line might break the page rendering completely ;-) (same as in https://github.com/Codeception/module-symfony/pull/119) - is there a way to escape this?

2021-03-15 15:16 UTC, TavoNiievez requested changes

2021-03-15 15:16 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/MailerAssertionsTrait.php
> +     * /** @var array<int, \Symfony\Component\Mime\Email> $emails */
Please remove this @var annotation, you can't `*/` in the middle of a docblock

2021-03-15 16:11 UTC, ThomasLandauer commented on src/Codeception/Module/Symfony/MailerAssertionsTrait.php
> +     * /** @var array<int, \Symfony\Component\Mime\Email> $emails */
But I like the idea - it makes the code sample so nicely copy-pastable :-)
I now tried to escape it - according to https://stackoverflow.com/a/1439351/1668200
Let's see how this comes out - otherwise I'll change it back...

2021-03-15 16:40 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/MailerAssertionsTrait.php
> +     * /** @var array<int, \Symfony\Component\Mime\Email> $emails */
I would instead only change:
```diff
- * @return \Symfony\Component\Mime\Email[]
+ * @return array<int, \Symfony\Component\Mime\Email>
```

2021-03-15 22:40 UTC, TavoNiievez commented
@ThomasLandauer please resolve conflicts.

2021-03-16 12:21 UTC, ThomasLandauer commented
I started from scratch ;-)

2021-03-16 12:21 UTC, closed without merging