Symfony 6 support
Codeception/module-symfony pull request #157
Opened 2022-05-10 15:35 UTC by semaz

Hi @TavoNiievez. 
I replaced the authorization `guard` logic with a `authenticator`, because this is the recommended authentication type in the new symfony ([https://symfony.com/doc/current/security/custom_authenticator.html](https://symfony.com/doc/current/security/custom_authenticator.html)). 
Also changed methods `amLoggedInAs` and `getCurrentSession`.
Can you review it and test it?

2022-05-10 16:39 UTC, TavoNiievez requested changes

2022-05-10 16:39 UTC, TavoNiievez commented on composer.json
> +        "symfony/form": "^6.0",
It is not in our plans to remove support for Symfony 4.4 and 5.4 while they are [officially supported](https://symfony.com/releases), could you use "^4.4 | ^5.4 | ^6.0" instead?

2022-05-10 19:38 UTC, semaz commented on composer.json
> +        "symfony/form": "^6.0",
Fixed. I can only suggest checking the symphony version in code, because it is very different in version 6.

2022-05-10 19:39 UTC, semaz commented on src/Codeception/Module/Symfony.php
> +        'authenticator' => false
Reverted back this code and added comments

2022-05-10 19:39 UTC, semaz commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +        if ($this->_getContainer()->has('session')) {
Fixed

2022-05-10 19:56 UTC, TavoNiievez approved these changes
wow! looks pretty good now.
I'm going to merge it when I update the [test project](https://github.com/codeception/symfony-module-tests) and have a successful run, but for now it has my thumbs up.
Thank you!

2022-05-15 15:43 UTC, merged

2022-05-16 10:41 UTC, semaz commented
Please tell when you want to make a new release?

2022-05-17 12:51 UTC, Naktibalda commented
@TavoNiievez We can release it as 3.1.0, right?

2022-05-17 13:02 UTC, TavoNiievez commented
@Naktibalda no, form assertions and test project still need to be adapted

2022-05-27 22:48 UTC, TavoNiievez commented
@semaz [module-symfony 3.1](https://github.com/Codeception/module-symfony/releases/tag/3.1.0) was released with support for Symfony 6.0.
Thank you very much for your help.