Add seeEvent/dontSeeEvent event assertions
Codeception/module-symfony pull request #173
Opened 2023-12-11 22:24 UTC by xEdelweiss

Hi! This is a follow-up for #168. In this update, I've added the `seeEvent`/`dontSeeEvent` methods, which check if an event was dispatched without considering whether the listener processed it. 

This approach allows the assertion to cover both orphan and non-orphan events. Therefore, this should help keep tests "green" during development, especially in scenarios where listeners might be added after the event's introduction.

Additionally, this PR consolidates `assertEventTriggered` and `assertEventNotTriggered` into a single method to reduce duplication.

2023-12-18 22:04 UTC, TavoNiievez requested changes

2023-12-18 22:04 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/EventsAssertionsTrait.php
> +     * Orphan events are included. Use `dontSeeOrphanEvent` to exclude them.
Can you rewrite this comment block in a way that makes it a little more clear what it means that this assertion 'includes' orphan events and in which cases `dontSeeOrphanEvent` should be used instead?
Although I understand your code it is difficult for me to understand the use of these terms in the comment block.
The same applies for `seeEvent`*

2023-12-18 22:04 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/EventsAssertionsTrait.php
> +            $condition = false;
Could you use a more descriptive name for this variable?

2023-12-19 10:46 UTC, xEdelweiss commented on src/Codeception/Module/Symfony/EventsAssertionsTrait.php
> +     * Orphan events are included. Use `dontSeeOrphanEvent` to exclude them.
The idea was that `seeEvent` would let you know that the event was triggered, but not that it is non-orphan, so you need an additional call to `dontSeeOrphanEvent`. But then I messed it up while cleaning up.

I've removed "exclusion" from `dontSeeEvent` phpDoc as it cannot be applied there. And fixed the suggested method for `seeEvent`.

2023-12-19 11:06 UTC, xEdelweiss commented on src/Codeception/Module/Symfony/EventsAssertionsTrait.php
> +            $condition = false;
Done. Hope it makes variable names clearer.

2023-12-19 13:04 UTC, TavoNiievez approved these changes

2023-12-20 13:30 UTC, merged