#165 login token
Codeception/module-symfony pull request #182
Opened 2024-02-04 17:20 UTC by codedge

2024-02-04 18:05 UTC, TavoNiievez requested changes

2024-02-04 18:05 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +    private function loginWithToken(TokenInterface $token, string $firewallName = 'main', string $firewallContext = null): void
This function should be `protected` because the inheritance of the `Codeception\Module\Symfony` class is allowed and this method encapsulates a useful independent functionality,
on the other hand, unlike `amLoggedInAs` and `amLoggedInWithToken` none of its parameters should have default values because its invocation already carries a default parameter.

2024-02-04 18:10 UTC, TavoNiievez commented
There are errors unrelated to this PR in the GitHub Actions.
When I have some time I'll see how I can fix them.
For the time being, I would appreciate if you could add a test for this new method in the module test project [symfony-module-tests](https://github.com/codeception/symfony-module-tests) (See the [contribution guide](https://github.com/Codeception/module-symfony/blob/main/CONTRIBUTING.md)).

Thanks!

2024-02-04 20:04 UTC, codedge commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +    private function loginWithToken(TokenInterface $token, string $firewallName = 'main', string $firewallContext = null): void
Make sense, applied.

2024-03-12 02:36 UTC, TavoNiievez requested changes

2024-03-12 02:36 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +        $this->loginWithToken($token, $firewallContext, $firewallName);
The order of the arguments does not seem to match the signature of the method below,
the tests fail because of:

> [TypeError] Codeception\Module\Symfony::loginWithToken(): Argument 2 ($firewallName) must be of type string, null given, called in .../SessionAssertionsTrait.php on line 38

2024-03-12 02:37 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +        $this->loginWithToken($token, $firewallContext, $firewallName);
@codedge tests are running again, so work on this RP can continue.

2024-03-12 02:45 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +        $this->loginWithToken($token, $firewallContext, $firewallName);
@codedge tests are running again, so work on this PR can continue.

2024-05-02 03:53 UTC, TavoNiievez commented on src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> +        $this->loginWithToken($token, $firewallContext, $firewallName);
I fixed this myself, but there are still a few things I'm going to double check before merging this.

2024-05-02 14:12 UTC, merged