Added seeUserPasswordIsEncoded function
Codeception/module-symfony pull request #29
Opened 2020-11-07 15:52 UTC by TavoNiievez

Method to verify that a user's password is encrypted.
If the user is not specified it is taken from the session.
The plain password can be specified as a parameter for even more accurate verification.

2020-11-13 21:19 UTC, DavertMik commented
I don't understand the context fully. 
Could you specify where this method should be used?

2020-11-13 21:19 UTC, DavertMik approved these changes

2020-11-14 14:00 UTC, TavoNiievez commented
Sure. This method is useful after persisting entities that implement the `UserInterface`, for example when registering a new user, or updating their password,

With this function you can verify that the password is correctly encrypted with the best available algorithm. (that is, the listener or event that you wrote to encode the user's password is working correctly.)

2020-11-16 07:11 UTC, Naktibalda requested changes

2020-11-16 07:11 UTC, Naktibalda commented on src/Codeception/Module/Symfony.php
> +     * Checks that the user's password is encrypted
I find it odd that Symfony decided to name this feature password encoding
but using word "encrypted" is worse, because encrypting passwords is bad practice, they must be hashed.
I looked at Symfony Security component and it hashes passwords, except PlaintextPasswordEncoder.

2020-11-16 07:11 UTC, Naktibalda commented on src/Codeception/Module/Symfony.php
> +        $this->assertFalse($needsRehash);
Your description says that this method `Checks that the user's password is encrypted`,
but I don't see that in the code.

If the second parameter is provided, this method checks if the password is correct.
otherwise it marks test as incomplete if password needs rehashing.

The behaviour of this method just doesn't match description,  
I would replace it with 2 separate methods - seeUserPasswordIsValid and skipTestIfPasswordNeedsRehash.

2020-11-16 14:31 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +        $this->assertFalse($needsRehash);
@Naktibalda Thank you!
Symfony does not provide a method to directly check if *a password **is** encoded*.

If for example, i have a password encoded with bcrypt, `needsRehash` would return `true`, because there are better algorithms like `argon2`... so i changed the name of the function.

Now there are **no** intermediate results with `markTestIncomplete` and i think that verifying that the password is encoded with the best possible algorithm is the only thing i want to assert.

2020-11-16 14:38 UTC, TavoNiievez commented on src/Codeception/Module/Symfony.php
> +     * Checks that the user's password is encrypted
It's called 'encode' for historical reasons [[1](https://symfony.com/blog/new-in-symfony-4-3-native-password-encoder)], i agree that using 'encrypt' left even more room for improvement.

However in the new description there is no mention of that word, thank you for letting me know.

2020-11-16 16:26 UTC, merged